
card_types:
  "10": "Character"
  "50": "Equipment"
  "30": "Artifact"
  "20": "Spell"
  "40": "Secret"
  "5": "Hero"

fields:
  - team
  - type
  - title
  - text
  - mana
  - attack
  - hp
#  - stats

output_format: table  # Can be 'csv' or 'table'

team_overrides:
  "Fire": "Humans"
  "Forest": "Eryxians"
  "Ancients": "The Ancients"

headers:
  "type": "Card Type"
  "team": "Faction"
  "title": "Card Name"
  "text": "Card Text"
  "mana": "Cost"
  "attack": "Attack"
  "hp": "HP"
#  "stats": "Stats"
