card_types:
  "10": "Character"
  "50": "Equipment"
  "30": "Artifact"
  "20": "Spell"
  "40": "Secret"
  "5": "Hero"

fields:
  - type
  - team
  - title
  - text
  - mana
  - attack
  - hp  # Keep mana, attack, hp if you want them as separate columns
#  - stats

output_format: table  # Or 'csv'

team_overrides:
  "Fire": "Humans"
  "Forest": "Eryxians"
  "Ancients": "The Ancients"

headers:
  "type": "Card Type"
  "team": "Faction"
  "title": "Card Name"
  "text": "Card Text"
  "mana": "Cost"  # Keep these if you want separate columns
  "attack": "Attack"
  "hp": "HP"
#  "stats": "Stats"  # Add a header for 'stats'
   # No 'stats' header!