
card_types:
  "10": "Character"
  "50": "Equipment"
  "30": "Artifact"
  "20": "Spell"
  "40": "Secret"
  "5": "Hero"

fields:
  - type
  - team
  - title
  - text
  - mana
  - attack
  - hp

output_format: table  # Can be 'csv' or 'table'

team_overrides:
  "Fire": "Humans"
  "Forest": "Eryxians"
  "Ancients": "The Ancients"

headers:
  - "Card Type"
  - "Faction"
  - "Card Name"
  - "Card Text"
  - "Stats"
